name: On PR

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
    secrets: inherit
  spdx:
    uses: ./.github/workflows/spdx.yml
    secrets: inherit
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit

  # When a PR runs on the uplift branch trigger the downstream checks
  downstream-checks:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.head.ref == 'uplift'
    env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Trigger tt-forge-fe
        shell: bash
        run: |
          gh workflow run build-and-test.yml \
            --repo tenstorrent/tt-forge-fe --ref main \
            --field test_mark=push \
            --field mlir_override=${{ github.sha }}
          gh run list --workflow=build-and-test.yml --repo tenstorrent/tt-forge-fe --limit 1
